# Generated by Django 3.2 on 2023-10-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='head_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='head_img',
            new_name='avatar',
        ),
    ]
